baseURL = "https://zakkau.github.io/"
title = "Zakk"
theme = "blowfish"

defaultContentLanguage = "en"
enableRobotsTXT = true
paginate = 10
canonifyURLs = true
mainSections = ["posts"]

enableGitInfo = true        # 供 .Lastmod / updated
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = false
  minifyOutput = true

[sitemap]
  changefreq = "weekly"
  priority = 0.6
  filename = "sitemap.xml"

[permalinks]
  posts = "/posts/:slug/"
  about = "/about/"

[outputs]
  home = ["HTML","RSS","JSON"]

[markup.goldmark.renderer]
  unsafe = true

[disableKinds]
  # 如無需 taxonomy 列表或分類頁可放開
  # "taxonomy"
  # "term"
