baseURL = "https://zakkau.github.io/"
languageCode = "en"
title = "Zakk"
theme = "blowfish"
defaultContentLanguage = "en"
enableRobotsTXT = true
paginate = 10
# 若未來要相對路徑可開啟：
# relativeURLs = true
# uglyURLs = false

[outputs]
  home = ["HTML","RSS","JSON"]

[permalinks]
  posts = "/posts/:slug/"
  about = "/about/"

[markup.goldmark.renderer]
  unsafe = true
