colorScheme = "neon"
# 若擔心首次載入延遲可先設為 true
disableImageOptimization = false
defaultBackgroundImage = "image.jpg"

# 社群分享圖（可自訂）
favicon = "favicon.ico"

[homepage]
  layout = "background"
  homepageImage = "image.jpg"
  showRecent = true
  showRecentItems = 8
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[header]
  layout = "fixed"

[article]
  showHero = true
  heroStyle = "background"
  showSummary = true
  showTableOfContents = true
  showAuthor = true
  showReadingTime = true
  showRelatedContent = true
  relatedContentLimit = 3
  showComments = false

[list]
  showCards = true
  groupByYear = true
  cardView = true

[footer]
  showCopyright = true

[features]
  enableSearch = true
  enableCodeCopy = true

[sharing]
  enabled = true
  twitter = true
  telegram = true

[taxonomy]
  showTermCount = true
