# 外觀
colorScheme = "neon"
defaultAppearance = "auto"          # 原 defaultTheme = auto
disableImageOptimization = false
defaultBackgroundImage = "image.jpg"
favicon = "favicon.ico"

# 自訂靜態資源（請建立對應檔案）
additionalCSS = ["css/header-buttons.css"]
additionalJS  = ["js/header-buttons.js"]

[homepage]
  layout = "background"
  homepageImage = "image.jpg"
  showRecent = true
  showRecentItems = 8
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[header]
  layout = "fixed"

[article]
  showHero = true
  heroStyle = "background"
  showSummary = true
  showTableOfContents = true
  showAuthor = true
  showReadingTime = true          # 映射 ShowReadingTime
  showBreadcrumbs = true          # 映射 ShowBreadCrumbs
  showRelatedContent = true
  relatedContentLimit = 3
  showEdit = false
  # Blowfish 沒有直接對應 ShowPostNavLinks，若要上下篇導覽：
  showPagination = true

[list]
  showCards = true
  groupByYear = true
  cardView = true
  showBreadcrumbs = true

[footer]
  showCopyright = true

[features]
  enableSearch = true
  enableCodeCopy = true            # 映射 ShowCodeCopyButtons

[sharing]
  enabled = false                  # 舊站 ShowShareButtons = false
  twitter = false
  telegram = false

[taxonomy]
  showTermCount = true
